<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code.

namespace Tests\Store\Action\Query;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\Store\Action\Query\CheckStoreExistsQry;
use Module\Store\Model\Store;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class CheckStoreExistsQryTest extends TestCase
{
    use DatabaseTransactions;

    private CheckStoreExistsQry $sut;

    private const int STORE_ID = 400;

    protected function setUp(): void
    {
        parent::setUp();

        $this->sut = new CheckStoreExistsQry;
    }

    #[Test, DataProvider('dataProviderCheck')]
    public function check(
        bool $createStore,
        bool $expected
    ): void {
        if ($createStore) {
            Store::forceCreate([
                'id' => self::STORE_ID,
                'external_id' => 'r400',
                'name' => 'Test Store',
                'address' => 'ul. Testowa 1',
            ]);
        }

        $result = $this->sut->check(self::STORE_ID);

        $this->assertSame($expected, $result);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderCheck(): array
    {
        return [
            'returns true when store exists' => [
                'createStore' => true,
                'expected' => true,
            ],
            'returns false when store does not exist' => [
                'createStore' => false,
                'expected' => false,
            ],
        ];
    }
}
