<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code.

namespace Tests\Store\Action\Query;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\Store\Action\Dto\StoreShortDto;
use Module\Store\Action\Query\GetStoreListQry;
use Module\Store\Model\Store;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class GetStoreListQryTest extends TestCase
{
    use DatabaseTransactions;

    private GetStoreListQry $sut;

    protected function setUp(): void
    {
        parent::setUp();

        $this->sut = new GetStoreListQry;

        Store::query()->forceDelete();
    }

    /**
     * @param  array<string, mixed>[]  $storesData
     * @param  StoreShortDto[]  $expected
     */
    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        array $storesData,
        array $expected,
    ): void {
        foreach ($storesData as $storeData) {
            Store::forceCreate($storeData);
        }

        $result = $this->sut->handle();

        $this->assertEquals($expected, $result);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'returns empty array when no stores exist' => [
                'storesData' => [],
                'expected' => [],
            ],
            'returns stores ordered by name' => [
                'storesData' => [
                    ['id' => 401, 'external_id' => 'r401', 'name' => 'Zielona Góra', 'address' => 'ul. Zielona 1'],
                    ['id' => 402, 'external_id' => 'r402', 'name' => 'Kraków', 'address' => 'ul. Krakowska 1'],
                    ['id' => 403, 'external_id' => 'r403', 'name' => 'Warszawa', 'address' => 'ul. Warszawska 1'],
                ],
                'expected' => [
                    new StoreShortDto(id: 402, externalId: 'r402', name: 'Kraków'),
                    new StoreShortDto(id: 403, externalId: 'r403', name: 'Warszawa'),
                    new StoreShortDto(id: 401, externalId: 'r401', name: 'Zielona Góra'),
                ],
            ],
        ];
    }
}
