<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code (with manual adjustments).

namespace Tests\Store\Action\Query;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\Store\Action\Dto\StoreShortDto;
use Module\Store\Action\Query\GetStoreByExternalIdQry;
use Module\Store\Model\Store;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class GetStoreByExternalIdQryTest extends TestCase
{
    use DatabaseTransactions;

    private GetStoreByExternalIdQry $sut;

    protected function setUp(): void
    {
        parent::setUp();

        $this->sut = new GetStoreByExternalIdQry;
        $this->prepareDb();
    }

    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        string $extId,
        ?StoreShortDto $expected,
    ): void {
        $result = $this->sut->handle($extId);

        $this->assertEquals($expected, $result);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'returns dto when store found' => [
                'extId' => 'r400',
                'expected' => new StoreShortDto(
                    id: 400,
                    externalId: 'r400',
                    name: 'Test Store',
                ),
            ],
            'returns null when store not found' => [
                'extId' => 'r401',
                'expected' => null,
            ],
        ];
    }

    private function prepareDb(): void
    {
        Store::forceCreate([
            'id' => 400,
            'external_id' => 'r400',
            'name' => 'Test Store',
            'address' => 'ul. Testowa 1',
        ]);
    }
}
