<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code.

namespace Tests\Store\Action\Query;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\Store\Action\Dto\StoreDto;
use Module\Store\Action\Query\GetStoreDetailsQry;
use Module\Store\Model\Store;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class GetStoreDetailsQryTest extends TestCase
{
    use DatabaseTransactions;

    private GetStoreDetailsQry $sut;

    private const int STORE_ID = 400;

    protected function setUp(): void
    {
        parent::setUp();

        $this->sut = new GetStoreDetailsQry;
    }

    /**
     * @param  array<string, mixed>|null  $storeData
     */
    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        ?array $storeData,
        ?StoreDto $expected,
        bool $expectedException = false
    ): void {
        if ($storeData) {
            Store::forceCreate(['id' => self::STORE_ID, ...$storeData]);
        }

        if ($expectedException) {
            $this->expectException(ModelNotFoundException::class);
        }

        $result = $this->sut->handle(self::STORE_ID);

        $this->assertEquals($expected, $result);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'returns dto when store found' => [
                'storeData' => [
                    'external_id' => 'r400',
                    'name' => 'Test Store',
                    'address' => 'ul. Testowa 1',
                ],
                'expected' => new StoreDto(
                    id: self::STORE_ID,
                    externalId: 'r400',
                    name: 'Test Store',
                    address: 'ul. Testowa 1',
                ),
            ],
            'store not found' => [
                'storeData' => null,
                'expected' => null,
                'expectedException' => true,
            ],
        ];
    }
}
