<?php
/** @noinspection PhpUnusedParameterInspection */
declare(strict_types=1);

// Test generated by Claude Code.

namespace Tests\Store\Access\Controller;

use Module\Customer\Support\TokenService;
use Module\Store\Access\Controller\StoreController;
use Module\Store\Action\Query\GetStoreDetailsQry;
use Module\Store\Action\Query\GetStoreListQry;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

#[CoversClass(StoreController::class)]
class StoreControllerTest extends TestCase
{
    /**
     * @param  class-string  $action
     * @param  array<string, mixed>  $dto
     */
    #[Test, DataProvider('dataProviderEndpoints')]
    public function blockAccessWithoutValidToken(
        string $method,
        string $path,
        string $action,
        array $dto,
        int $expected,
    ): void {
        $mock = $this->createStub($action);
        $this->instance($action, $mock);

        $response = $this->withoutToken()->json($method, '/api' . $path, $dto);
        $response->assertUnauthorized();
    }

    /**
     * @param  class-string  $action
     * @param  array<string, mixed>  $dto
     */
    #[Test, DataProvider('dataProviderEndpoints')]
    public function blockAccessWithInvalidToken(
        string $method,
        string $path,
        string $action,
        array $dto,
        int $expected,
    ): void {
        $mock = $this->createStub($action);
        $this->instance($action, $mock);

        $response = $this->withToken('BAD_TOKEN')->json($method, '/api' . $path, $dto);
        $response->assertUnauthorized();
    }

    /**
     * @param  class-string  $action
     * @param  array<string, mixed>  $dto
     */
    #[Test, DataProvider('dataProviderEndpoints')]
    public function allowWithValidToken(
        string $method,
        string $path,
        string $action,
        array $dto,
        int $expected,
    ): void {
        $token = new TokenService(app('config'))->newAccessToken(1, 10);
        $mock = $this->createStub($action);
        $this->instance($action, $mock);

        $response = $this->withToken($token)->json($method, '/api' . $path, $dto);

        $this->assertEquals($expected, $response->getStatusCode());
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public static function dataProviderEndpoints(): array
    {
        return [
            [
                'method' => 'get',
                'path' => '/store/list',
                'action' => GetStoreListQry::class,
                'dto' => [],
                'expected' => 200,
            ],
            [
                'method' => 'get',
                'path' => '/store/25',
                'action' => GetStoreDetailsQry::class,
                'dto' => [],
                'expected' => 200,
            ],
        ];
    }
}
