<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code (with manual adjustments).

namespace Tests\User\Action\Command;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\User\Action\Command\AdminLoginCmd;
use Module\User\Action\Dto\AdminLoginRequestDto;
use Module\User\Model\User;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class AdminLoginCmdTest extends TestCase
{
    use DatabaseTransactions;

    private AdminLoginCmd $sut;

    private const string EMAIL = 'test@my.company.com';

    protected function setUp(): void
    {
        parent::setUp();

        $this->sut = new AdminLoginCmd;
    }

    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        bool $createUser,
        int $expectedUserCount,
    ): void {
        if ($createUser) {
            User::factory()->create(['email' => self::EMAIL]);
        }
        else {
            $userCountBefore = User::query()->where('email', self::EMAIL)->count();
            $this->assertEquals(0, $userCountBefore);
        }

        $result = $this->sut->handle(new AdminLoginRequestDto(email: self::EMAIL));

        $this->assertNotEmpty($result->token);
        $this->assertEquals(
            $expectedUserCount,
            User::query()->where('email', self::EMAIL)->count(),
        );
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'creates new user and returns token when user does not exist' => [
                'createUser' => false,
                'expectedUserCount' => 1,
            ],
            'returns token for existing user without creating duplicate' => [
                'createUser' => true,
                'expectedUserCount' => 1,
            ],
        ];
    }
}
