<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code (with manual adjustments).

namespace Tests\Product\Action\Query;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\Product\Action\Dto\ProductDetailsDto;
use Module\Product\Action\Query\GetProductDetailsQry;
use Module\Product\Model\Product;
use Module\Product\Model\ProductQuantity;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class GetProductDetailsQryTest extends TestCase
{
    use DatabaseTransactions;

    private GetProductDetailsQry $sut;

    private const int PRODUCT_ID = 200;

    private const int STORE_ID = 5;

    protected function setUp(): void
    {
        parent::setUp();

        $this->sut = new GetProductDetailsQry;
    }

    /**
     * @param  array<string, mixed>  $productData
     * @param  array<string, mixed>|null  $quantityData
     */
    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        ?array $productData,
        ?array $quantityData,
        ProductDetailsDto $expected,
        bool $expectedException = false
    ): void {
        if ($productData) {
            Product::forceCreate(['id' => self::PRODUCT_ID, ...$productData]);
        }
        if ($quantityData) {
            ProductQuantity::forceCreate([
                'product_id' => self::PRODUCT_ID,
                'store_id' => self::STORE_ID,
                ...$quantityData,
            ]);
        }

        if ($expectedException) {
            $this->expectException(ModelNotFoundException::class);
        }

        $result = $this->sut->handle(self::PRODUCT_ID, self::STORE_ID);

        $this->assertEquals($expected, $result);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'product with quantity and image' => [
                'productData' => [
                    'ean' => '8410564006257',
                    'name' => 'Red square',
                    'image_url' => 'https://my.images.com/red-square.png',
                ],
                'quantityData' => [
                    'quantity' => 7000,
                ],
                'expected' => new ProductDetailsDto(
                    id: self::PRODUCT_ID,
                    ean: '8410564006257',
                    name: 'Red square',
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantity: 7000,
                ),
            ],
            'product without quantity record' => [
                'productData' => [
                    'ean' => '8410564006257',
                    'name' => 'Red square',
                    'image_url' => 'https://my.images.com/red-square.png',
                ],
                'quantityData' => null,
                'expected' => new ProductDetailsDto(
                    id: self::PRODUCT_ID,
                    ean: '8410564006257',
                    name: 'Red square',
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantity: null,
                ),
            ],
            'product without image url' => [
                'productData' => [
                    'ean' => '1234567890123',
                    'name' => 'Blue circle',
                    'image_url' => null,
                ],
                'quantityData' => [
                    'quantity' => 50,
                ],
                'expected' => new ProductDetailsDto(
                    id: self::PRODUCT_ID,
                    ean: '1234567890123',
                    name: 'Blue circle',
                    imageUrl: null,
                    quantity: 50,
                ),
            ],
            'product not found' => [
                'productData' => null,
                'quantityData' => null,
                'expected' => new ProductDetailsDto(1, '', '', null, null),
                'expectedException' => true,
            ],
        ];
    }
}
