<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code.

namespace Tests\Product\Action\Query;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\Product\Action\Dto\ProductShortDto;
use Module\Product\Action\Query\GetProductByEansQry;
use Module\Product\Model\Product;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class GetProductByEansQryTest extends TestCase
{
    use DatabaseTransactions;

    private GetProductByEansQry $sut;

    protected function setUp(): void
    {
        parent::setUp();

        $this->sut = new GetProductByEansQry;
    }

    /**
     * @param  array<string, mixed>[]  $products
     * @param  string[]  $eans
     * @param  ProductShortDto[]  $expected
     */
    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        array $products,
        array $eans,
        array $expected,
    ): void {
        foreach ($products as $product) {
            Product::forceCreate($product);
        }

        $result = $this->sut->handle($eans);

        $this->assertEqualsCanonicalizing($expected, $result);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'returns matching products' => [
                'products' => [
                    ['id' => 301, 'ean' => '8410564006257', 'name' => 'Red square', 'image_url' => null],
                    ['id' => 302, 'ean' => '1234567890123', 'name' => 'Blue circle', 'image_url' => null],
                    ['id' => 303, 'ean' => '9999999999999', 'name' => 'Other product', 'image_url' => null],
                ],
                'eans' => ['8410564006257', '1234567890123'],
                'expected' => [
                    new ProductShortDto(id: 301, ean: '8410564006257'),
                    new ProductShortDto(id: 302, ean: '1234567890123'),
                ],
            ],
            'returns empty array for empty eans input' => [
                'products' => [
                    ['id' => 301, 'ean' => '8410564006257', 'name' => 'Red square', 'image_url' => null],
                ],
                'eans' => [],
                'expected' => [],
            ],
            'returns empty array when no eans match' => [
                'products' => [
                    ['id' => 301, 'ean' => '8410564006257', 'name' => 'Red square', 'image_url' => null],
                ],
                'eans' => ['0000000000000'],
                'expected' => [],
            ],
        ];
    }
}
