<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code (with manual adjustments).

namespace Tests\Offer\Action\Command;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\Offer\Action\Command\ChangeVisibilityCmd;
use Module\Offer\Action\Dto\Admin\ChangeVisibilityDto;
use Module\Offer\Model\Offer;
use Module\Shared\Exception\AppEntityVersionException;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class ChangeVisibilityCmdTest extends TestCase
{
    use DatabaseTransactions;

    private ChangeVisibilityCmd $sut;

    private const int OFFER_ID = 100;

    private const int OFFER2_ID = 101;

    private const int MISSING_OFFER_ID = 999;

    private const int CURRENT_VERSION = 2;

    protected function setUp(): void
    {
        parent::setUp();

        $this->sut = new ChangeVisibilityCmd;
        $this->prepareDb();
    }

    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        int $id,
        int $version,
        bool $visible,
        string $expectedException,
        bool $expectedVisible,
        int $expectedVersion,
    ): void {
        if ($expectedException) {
            $this->expectException($expectedException);
        }

        $this->sut->handle(new ChangeVisibilityDto($id, $version, $visible));

        $this->assertDatabaseHas(Offer::class, [
            'id' => $id,
            'visible' => $expectedVisible,
            'version' => $expectedVersion,
        ]);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'visible to invisible' => [
                'id' => self::OFFER_ID,
                'version' => self::CURRENT_VERSION,
                'visible' => false,
                'expectedException' => '',
                'expectedVisible' => false,
                'expectedVersion' => self::CURRENT_VERSION + 1,
            ],
            'invisible to visible' => [
                'id' => self::OFFER2_ID,
                'version' => self::CURRENT_VERSION,
                'visible' => true,
                'expectedException' => '',
                'expectedVisible' => true,
                'expectedVersion' => self::CURRENT_VERSION + 1,
            ],
            'no-op same visibility still increments version' => [
                'id' => self::OFFER_ID,
                'version' => self::CURRENT_VERSION,
                'visible' => true,
                'expectedException' => '',
                'expectedVisible' => true,
                'expectedVersion' => self::CURRENT_VERSION + 1,
            ],
            'version mismatch' => [
                'id' => self::OFFER_ID,
                'version' => self::CURRENT_VERSION + 1,
                'visible' => false,
                'expectedException' => AppEntityVersionException::class,
                'expectedVisible' => true,
                'expectedVersion' => self::CURRENT_VERSION,
            ],
            'offer not found' => [
                'id' => self::MISSING_OFFER_ID,
                'version' => self::CURRENT_VERSION,
                'visible' => false,
                'expectedException' => ModelNotFoundException::class,
                'expectedVisible' => true,
                'expectedVersion' => self::CURRENT_VERSION,
            ],
        ];
    }

    private function prepareDb(): void
    {
        Offer::forceCreate([
            'id' => self::OFFER_ID,
            'version' => self::CURRENT_VERSION,
            'store_id' => 5,
            'external_id' => 'ex-1',
            'product_ean' => 'ean-1',
            'product_name' => null,
            'price' => 10000,
            'lowest_price' => 12000,
            'visible' => true,
            'product_id' => 50,
        ]);
        Offer::forceCreate([
            'id' => self::OFFER2_ID,
            'version' => self::CURRENT_VERSION,
            'store_id' => 5,
            'external_id' => 'ex-2',
            'product_ean' => 'ean-2',
            'product_name' => null,
            'price' => 10000,
            'lowest_price' => null,
            'visible' => false,
            'product_id' => 50,
        ]);
    }
}
