<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code (with manual adjustments).

namespace Tests\Offer\Action\Query;

use Module\Offer\Action\Dto\Admin\StoreDto;
use Module\Offer\Action\Query\AdminGetListFiltersQry;
use Module\Store\Action\Dto\StoreShortDto;
use Module\Store\Action\Query\GetStoreListQry;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\MockObject\MockObject;
use Tests\TestCase;

class AdminGetListFiltersQryTest extends TestCase
{
    private AdminGetListFiltersQry $sut;

    private MockObject|GetStoreListQry $getStoreListQry;

    protected function setUp(): void
    {
        parent::setUp();

        $this->getStoreListQry = $this->createStub(GetStoreListQry::class);

        $this->sut = new AdminGetListFiltersQry(
            $this->getStoreListQry,
        );
    }

    /**
     * @param  StoreShortDto[]  $storeList
     * @param  StoreDto[]  $expected
     */
    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        array $storeList,
        array $expected,
    ): void {
        $this->getStoreListQry->method('handle')->willReturn($storeList);

        $result = $this->sut->handle();

        $this->assertEquals($expected, $result->stores);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'empty' => [
                'storeList' => [],
                'expected' => [],
            ],
            'multiple stores' => [
                'storeList' => [
                    new StoreShortDto(id: 5, externalId: 'r002', name: 'Luboń'),
                    new StoreShortDto(id: 7, externalId: 'r004', name: 'Poznań'),
                ],
                'expected' => [
                    new StoreDto(storeId: 5, storeName: 'Luboń'),
                    new StoreDto(storeId: 7, storeName: 'Poznań'),
                ],
            ],
        ];
    }
}
