<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code (with manual adjustments).

namespace Tests\Offer\Action\Query;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\Offer\Action\Dto\Admin\OfferDto;
use Module\Offer\Action\Query\AdminGetOfferDetailsQry;
use Module\Offer\Model\Offer;
use Module\Product\Action\Dto\ProductDetailsDto;
use Module\Product\Action\Query\GetProductDetailsQry;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\MockObject\MockObject;
use Tests\TestCase;

class AdminGetOfferDetailsQryTest extends TestCase
{
    use DatabaseTransactions;

    private AdminGetOfferDetailsQry $sut;

    private MockObject|GetProductDetailsQry $getProductDetailsQry;

    private const int OFFER_ID = 100;

    protected function setUp(): void
    {
        parent::setUp();

        $this->getProductDetailsQry = $this->createStub(GetProductDetailsQry::class);

        $this->sut = new AdminGetOfferDetailsQry(
            $this->getProductDetailsQry,
        );
    }

    /**
     * @param  array<string, mixed>  $offerData
     */
    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        array $offerData,
        ?ProductDetailsDto $product,
        OfferDto $expected,
    ): void {
        Offer::forceCreate(['id' => self::OFFER_ID, ...$offerData]);
        if ($product) {
            $this->getProductDetailsQry->method('handle')->willReturn($product);
        }

        $result = $this->sut->handle(self::OFFER_ID);

        $this->assertEquals($expected, $result);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'product name taken from product' => [
                'offerData' => [
                    'version' => 1,
                    'store_id' => 5,
                    'external_id' => 'e001',
                    'product_ean' => '8410564006257',
                    'product_name' => null,
                    'price' => 805,
                    'lowest_price' => 800,
                    'visible' => true,
                    'product_id' => 50,
                ],
                'product' => new ProductDetailsDto(
                    id: 50,
                    ean: '8410564006257',
                    name: 'Red square',
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantity: 7000,
                ),
                'expected' => new OfferDto(
                    id: self::OFFER_ID,
                    version: 1,
                    visible: true,
                    productEan: '8410564006257',
                    productName: 'Red square',
                    price: 805,
                    lowestPrice: 800,
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantity: 7000,
                ),
            ],
            'product name taken from offer' => [
                'offerData' => [
                    'version' => 2,
                    'store_id' => 5,
                    'external_id' => 'e002',
                    'product_ean' => '8410564006257',
                    'product_name' => 'Override name',
                    'price' => 1000,
                    'lowest_price' => null,
                    'visible' => false,
                    'product_id' => 50,
                ],
                'product' => new ProductDetailsDto(
                    id: 50,
                    ean: '8410564006257',
                    name: 'Red square',
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantity: null,
                ),
                'expected' => new OfferDto(
                    id: self::OFFER_ID,
                    version: 2,
                    visible: false,
                    productEan: '8410564006257',
                    productName: 'Override name',
                    price: 1000,
                    lowestPrice: null,
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantity: null,
                ),
            ],
            'offer without product' => [
                'offerData' => [
                    'version' => 2,
                    'store_id' => 5,
                    'external_id' => 'e002',
                    'product_ean' => '8410564006257',
                    'product_name' => 'Override name',
                    'price' => 1000,
                    'lowest_price' => null,
                    'visible' => false,
                    'product_id' => null,
                ],
                'product' => null,
                'expected' => new OfferDto(
                    id: self::OFFER_ID,
                    version: 2,
                    visible: false,
                    productEan: '8410564006257',
                    productName: 'Override name',
                    price: 1000,
                    lowestPrice: null,
                    imageUrl: '',
                    quantity: null,
                ),
            ],
        ];
    }
}
