<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code (with manual adjustments).

namespace Tests\Offer\Action\Query;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\Offer\Action\Dto\Admin\ListParamDto;
use Module\Offer\Action\Dto\Admin\OfferShortDto;
use Module\Offer\Action\Query\AdminGetOfferListQry;
use Module\Offer\Model\Offer;
use Module\Product\Action\Query\JoinProductByIdSqlQry;
use Module\Product\Model\Product;
use Module\Store\Action\Query\JoinStoreByIdSqlQry;
use Module\Store\Model\Store;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class AdminGetOfferListQryTest extends TestCase
{
    use DatabaseTransactions;

    private AdminGetOfferListQry $sut;

    private const int STORE_ID = 10;

    private const int STORE2_ID = 11;

    protected function setUp(): void
    {
        parent::setUp();

        $this->sut = new AdminGetOfferListQry(
            resolve(JoinProductByIdSqlQry::class),
            resolve(JoinStoreByIdSqlQry::class),
        );
        $this->prepareDb();
    }

    /**
     * @param  OfferShortDto[]  $expectedItems
     */
    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        ?string $search,
        ?int $storeId,
        ?int $page,
        ?int $perPage,
        array $expectedItems,
        int $expectedPage,
        int $expectedPerPage,
    ): void {
        $result = $this->sut->handle(new ListParamDto($search, $storeId, $page, $perPage));

        $this->assertEquals($expectedPage, $result->page);
        $this->assertEquals($expectedPerPage, $result->perPage);
        $this->assertEquals($expectedItems, $result->items);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'no filters - default page' => [
                'search' => null,
                'storeId' => null,
                'page' => null,
                'perPage' => null,
                'expectedItems' => [
                    new OfferShortDto(22, 'Luboń', true, 'ean-3', 'Standalone', 10002),
                    new OfferShortDto(21, 'Luboń', false, 'ean-2', 'Override circle', 10001),
                    new OfferShortDto(20, 'Luboń', true, 'ean-1', 'Red square', 10000),
                    new OfferShortDto(23, 'Poznań', true, 'ean-1', 'Red square', 10003),
                ],
                'expectedPage' => 1,
                'expectedPerPage' => 10,
            ],
            'filter by store' => [
                'search' => null,
                'storeId' => self::STORE2_ID,
                'page' => null,
                'perPage' => null,
                'expectedItems' => [
                    new OfferShortDto(23, 'Poznań', true, 'ean-1', 'Red square', 10003),
                ],
                'expectedPage' => 1,
                'expectedPerPage' => 10,
            ],
            'search by product name (override)' => [
                'search' => 'circle',
                'storeId' => null,
                'page' => null,
                'perPage' => null,
                'expectedItems' => [
                    new OfferShortDto(21, 'Luboń', false, 'ean-2', 'Override circle', 10001),
                ],
                'expectedPage' => 1,
                'expectedPerPage' => 10,
            ],
            'search by product name (from product)' => [
                'search' => 'square',
                'storeId' => null,
                'page' => null,
                'perPage' => null,
                'expectedItems' => [
                    new OfferShortDto(20, 'Luboń', true, 'ean-1', 'Red square', 10000),
                    new OfferShortDto(23, 'Poznań', true, 'ean-1', 'Red square', 10003),
                ],
                'expectedPage' => 1,
                'expectedPerPage' => 10,
            ],
            'search by ean' => [
                'search' => 'ean-3',
                'storeId' => null,
                'page' => null,
                'perPage' => null,
                'expectedItems' => [
                    new OfferShortDto(22, 'Luboń', true, 'ean-3', 'Standalone', 10002),
                ],
                'expectedPage' => 1,
                'expectedPerPage' => 10,
            ],
            'search no match' => [
                'search' => 'nothing-matches',
                'storeId' => null,
                'page' => null,
                'perPage' => null,
                'expectedItems' => [],
                'expectedPage' => 1,
                'expectedPerPage' => 10,
            ],
            'first page' => [
                'search' => null,
                'storeId' => null,
                'page' => 1,
                'perPage' => 2,
                'expectedItems' => [
                    new OfferShortDto(22, 'Luboń', true, 'ean-3', 'Standalone', 10002),
                    new OfferShortDto(21, 'Luboń', false, 'ean-2', 'Override circle', 10001),
                ],
                'expectedPage' => 1,
                'expectedPerPage' => 2,
            ],
            'second page' => [
                'search' => null,
                'storeId' => null,
                'page' => 2,
                'perPage' => 2,
                'expectedItems' => [
                    new OfferShortDto(20, 'Luboń', true, 'ean-1', 'Red square', 10000),
                    new OfferShortDto(23, 'Poznań', true, 'ean-1', 'Red square', 10003),
                ],
                'expectedPage' => 2,
                'expectedPerPage' => 2,
            ],
            'negative page' => [
                'search' => null,
                'storeId' => null,
                'page' => -1,
                'perPage' => 2,
                'expectedItems' => [
                    new OfferShortDto(22, 'Luboń', true, 'ean-3', 'Standalone', 10002),
                    new OfferShortDto(21, 'Luboń', false, 'ean-2', 'Override circle', 10001),
                ],
                'expectedPage' => 1,
                'expectedPerPage' => 2,
            ],
            'after last page' => [
                'search' => null,
                'storeId' => null,
                'page' => 5,
                'perPage' => 2,
                'expectedItems' => [],
                'expectedPage' => 5,
                'expectedPerPage' => 2,
            ],
        ];
    }

    private function prepareDb(): void
    {
        Store::forceCreate(['id' => self::STORE_ID, 'external_id' => 's-10', 'name' => 'Luboń', 'address' => 'addr 10']);
        Store::forceCreate(['id' => self::STORE2_ID, 'external_id' => 's-11', 'name' => 'Poznań', 'address' => 'addr 11']);

        Product::forceCreate(['id' => 50, 'ean' => 'ean-1', 'name' => 'Red square', 'image_url' => 'red-square.png']);
        Product::forceCreate(['id' => 51, 'ean' => 'ean-2', 'name' => 'Red circle', 'image_url' => 'red-circle.png']);

        Offer::forceCreate(['id' => 20, 'version' => 2, 'store_id' => self::STORE_ID, 'external_id' => 'ex-1', 'product_ean' => 'ean-1',
            'product_name' => null, 'price' => 10000, 'lowest_price' => 12000, 'visible' => true, 'product_id' => 50]);
        Offer::forceCreate(['id' => 21, 'version' => 2, 'store_id' => self::STORE_ID, 'external_id' => 'ex-2', 'product_ean' => 'ean-2',
            'product_name' => 'Override circle', 'price' => 10001, 'lowest_price' => 12001, 'visible' => false, 'product_id' => 51]);
        Offer::forceCreate(['id' => 22, 'version' => 2, 'store_id' => self::STORE_ID, 'external_id' => 'ex-3', 'product_ean' => 'ean-3',
            'product_name' => 'Standalone', 'price' => 10002, 'lowest_price' => null, 'visible' => true, 'product_id' => null]);
        Offer::forceCreate(['id' => 23, 'version' => 3, 'store_id' => self::STORE2_ID, 'external_id' => 'ex-23', 'product_ean' => 'ean-1',
            'product_name' => null, 'price' => 10003, 'lowest_price' => 12000, 'visible' => true, 'product_id' => 50]);
    }
}
