<?php
/** @noinspection PhpUnhandledExceptionInspection */
declare(strict_types=1);

// Test generated by Claude Code (with manual adjustments).

namespace Tests\Offer\Action\Query;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Module\Customer\Action\Query\GetCurrentCustomerStoreIdQry;
use Module\Offer\Action\Dto\OfferDto;
use Module\Offer\Action\Enum\QuantityLevelEnum;
use Module\Offer\Action\Query\GetOfferDetailsQry;
use Module\Offer\Model\Offer;
use Module\Product\Action\Dto\ProductDetailsDto;
use Module\Product\Action\Query\GetProductDetailsQry;
use Module\Shared\Exception\AppValidationException;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\MockObject\MockObject;
use Tests\TestCase;

class GetOfferDetailsQryTest extends TestCase
{
    use DatabaseTransactions;

    private GetOfferDetailsQry $sut;

    private MockObject|GetProductDetailsQry $getProductDetailsQry;

    private const int OFFER_ID = 100;

    private const int STORE_ID = 5;

    protected function setUp(): void
    {
        parent::setUp();

        $getCurrentCustomerStoreIdQry = $this->createStub(GetCurrentCustomerStoreIdQry::class);
        $getCurrentCustomerStoreIdQry->method('handle')->willReturn(self::STORE_ID);

        $this->getProductDetailsQry = $this->createStub(GetProductDetailsQry::class);

        $this->sut = new GetOfferDetailsQry(
            $getCurrentCustomerStoreIdQry,
            $this->getProductDetailsQry,
        );
    }

    /**
     * @param  array<string, mixed>  $offerData
     */
    #[Test, DataProvider('dataProviderHandle')]
    public function handle(
        array $offerData,
        ProductDetailsDto $product,
        OfferDto $expected,
    ): void {
        Offer::forceCreate(['id' => self::OFFER_ID, ...$offerData]);
        $this->getProductDetailsQry->method('handle')->willReturn($product);

        $result = $this->sut->handle(self::OFFER_ID);

        $this->assertEquals($expected, $result);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandle(): array
    {
        return [
            'product name taken from product, quantity available' => [
                'offerData' => [
                    'version' => 1,
                    'store_id' => self::STORE_ID,
                    'external_id' => 'e001',
                    'product_ean' => '8410564006257',
                    'product_name' => null,
                    'price' => 805,
                    'lowest_price' => 800,
                    'visible' => true,
                    'product_id' => 50,
                ],
                'product' => new ProductDetailsDto(
                    id: 50,
                    ean: '8410564006257',
                    name: 'Red square',
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantity: 7000,
                ),
                'expected' => new OfferDto(
                    id: self::OFFER_ID,
                    productEan: '8410564006257',
                    productName: 'Red square',
                    price: 805,
                    lowestPrice: 800,
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantityLevel: QuantityLevelEnum::AVAILABLE,
                ),
            ],
            'product name taken from offer, quantity available low' => [
                'offerData' => [
                    'version' => 2,
                    'store_id' => self::STORE_ID,
                    'external_id' => 'e002',
                    'product_ean' => '8410564006257',
                    'product_name' => 'Override name',
                    'price' => 1000,
                    'lowest_price' => null,
                    'visible' => true,
                    'product_id' => 50,
                ],
                'product' => new ProductDetailsDto(
                    id: 50,
                    ean: '8410564006257',
                    name: 'Red square',
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantity: 10,
                ),
                'expected' => new OfferDto(
                    id: self::OFFER_ID,
                    productEan: '8410564006257',
                    productName: 'Override name',
                    price: 1000,
                    lowestPrice: null,
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantityLevel: QuantityLevelEnum::AVAILABLE_LOW,
                ),
            ],
            'quantity unknown' => [
                'offerData' => [
                    'version' => 3,
                    'store_id' => self::STORE_ID,
                    'external_id' => 'e003',
                    'product_ean' => '8410564006257',
                    'product_name' => 'Override name',
                    'price' => 1000,
                    'lowest_price' => null,
                    'visible' => true,
                    'product_id' => 50,
                ],
                'product' => new ProductDetailsDto(
                    id: 50,
                    ean: '8410564006257',
                    name: 'Red square',
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantity: null,
                ),
                'expected' => new OfferDto(
                    id: self::OFFER_ID,
                    productEan: '8410564006257',
                    productName: 'Override name',
                    price: 1000,
                    lowestPrice: null,
                    imageUrl: 'https://my.images.com/red-square.png',
                    quantityLevel: QuantityLevelEnum::UNKNOWN,
                ),
            ],
        ];
    }

    /**
     * @param  array<string, mixed>|null  $offerData
     */
    #[Test, DataProvider('dataProviderHandleException')]
    public function handleException(
        ?array $offerData,
        string $expectedExceptionMessage,
    ): void {
        if ($offerData) {
            Offer::forceCreate(['id' => self::OFFER_ID, ...$offerData]);

            $this->expectException(AppValidationException::class);
            $this->expectExceptionMessageMatches('/^' . preg_quote($expectedExceptionMessage, '/') . '$/');
        }
        else {
            $this->expectException(ModelNotFoundException::class);
            $this->expectExceptionMessageMatches('/^' . preg_quote($expectedExceptionMessage, '/') . '/');
        }

        $this->sut->handle(self::OFFER_ID);
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function dataProviderHandleException(): array
    {
        return [
            'offer belongs to other store' => [
                'offerData' => [
                    'version' => 1,
                    'store_id' => self::STORE_ID + 1,
                    'external_id' => 'e001',
                    'product_ean' => '8410564006257',
                    'product_name' => null,
                    'price' => 805,
                    'lowest_price' => 800,
                    'visible' => true,
                    'product_id' => 50,
                ],
                'expectedExceptionMessage' => 'Requested offer belongs to other store.',
            ],
            'offer not visible' => [
                'offerData' => [
                    'version' => 1,
                    'store_id' => self::STORE_ID,
                    'external_id' => 'e001',
                    'product_ean' => '8410564006257',
                    'product_name' => null,
                    'price' => 805,
                    'lowest_price' => 800,
                    'visible' => false,
                    'product_id' => 50,
                ],
                'expectedExceptionMessage' => 'Requested offer is not visible.',
            ],
            'offer without product' => [
                'offerData' => [
                    'version' => 1,
                    'store_id' => self::STORE_ID,
                    'external_id' => 'e001',
                    'product_ean' => '8410564006257',
                    'product_name' => null,
                    'price' => 805,
                    'lowest_price' => 800,
                    'visible' => true,
                    'product_id' => null,
                ],
                'expectedExceptionMessage' => 'Requested offer is for unknown product.',
            ],
            'offer not found' => [
                'offerData' => [],
                'expectedExceptionMessage' => 'No query results for model',
            ],
        ];
    }
}
